Import webpack using "* as webpack" syntax.
Otherwise curtain typescript configuration might complain during "tsc --noEmit" with the following error:

```
node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCheckerWebpackPlugin.d.ts:1:8 - error TS1259: Module '"/Users/apepper/repos/scrivito_js/js/node_modules/@types/webpack/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

1 import webpack from 'webpack';
         ~~~~~~~

  node_modules/@types/webpack/index.d.ts:49:1
    49 export = webpack;
       ~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

node_modules/fork-ts-checker-webpack-plugin/lib/logger/LoggerFactory.d.ts:1:8 - error TS1259: Module '"/Users/apepper/repos/scrivito_js/js/node_modules/@types/webpack/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

1 import webpack from 'webpack';
         ~~~~~~~

  node_modules/@types/webpack/index.d.ts:49:1
    49 export = webpack;
       ~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.


Found 2 errors.
```