chore: import webpack using "* as webpack" syntax (#780)
Avoids problems like the following:

```
$ npx tsc
node_modules/fork-ts-checker-webpack-plugin/lib/plugin.d.ts:1:13 - error TS1259: Module '".../node_modules/webpack/types"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

1 import type webpack from 'webpack';
              ~~~~~~~

  node_modules/webpack/types.d.ts:13189:1
    13189 export = exports;
          ~~~~~~~~~~~~~~~~~
    This module is declared with 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

Found 1 error in node_modules/fork-ts-checker-webpack-plugin/lib/plugin.d.ts:1
```